package com.au10tix.au10sample;

public enum DetectionTypes {
    FACE_DETECTION,
    DOCUMENT_DETECTION,
    BARCODE_DETECTION,
    LIVENESS_DETECTION,
    LIVENESS2_DETECTION,
    DOCUMENT_DETECTION_CUSTOM_QUALITY_INDICATION,
    FACE_DETECTION_CUSTOM_CONTROLS,
    LIVENESS2_DETECTION_CUSTOM_UI
}
